# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-05 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='mode_payment',
            field=models.CharField(blank=True, choices=[('', 'Онлайн оплата отсутствует'), ('https://3dsec.sberbank.ru/payment/', 'Тестовый режим'), ('https://securepayments.sberbank.ru/payment/', 'Боевой режим')], default='', max_length=100, verbose_name='Режим оплаты'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='shop_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Логин api'),
        ),
    ]
