# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-25 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20180905_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='in_product_view',
            field=models.CharField(blank=True, choices=[('classic', 'Классик'), ('wide', 'Широкие')], max_length=300, verbose_name='Вид отображения похожих товаров'),
        ),
    ]
