# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-25 05:36
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_settings_in_product_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='color_scheme',
            field=colorfield.fields.ColorField(default='#FF0000', help_text='HEX color, as #RRGGBB', max_length=18, verbose_name='Цветовая схема сайта'),
        ),
    ]
