# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-25 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_settings_color_scheme_alpha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='color_scheme_alpha',
            field=models.CharField(blank=True, max_length=50, verbose_name='Цветовая схема c alpha'),
        ),
    ]
