# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-25 06:57
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_auto_20181025_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='color_scheme_dark',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цветовая схема затемнение'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='color_scheme',
            field=colorfield.fields.ColorField(default='#D40000', help_text='HEX color, as #RRGGBB', max_length=18, verbose_name='Цветовая схема сайта'),
        ),
    ]
