# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-25 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_auto_20181025_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='in_product_view',
            field=models.CharField(choices=[('classic', 'Классик'), ('wide', 'Широкие')], default='classic', max_length=300, verbose_name='Вид отображения похожих товаров'),
        ),
    ]
