# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-25 08:37
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_auto_20181025_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='social_view',
            field=models.CharField(choices=[('classic', 'Плитка'), ('column', 'Столбец')], default='classic', max_length=300, verbose_name='Вид отображения соц. сетей'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='color_scheme',
            field=colorfield.fields.ColorField(default='#006EFF', help_text='HEX color, as #RRGGBB', max_length=18, verbose_name='Цветовая схема сайта'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='color_scheme_alpha',
            field=models.CharField(blank=True, default='rgba(0, 110, 255, 0.6)', max_length=50, verbose_name='Цветовая схема c alpha'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='color_scheme_dark',
            field=models.CharField(blank=True, default='#000CD4', max_length=7, verbose_name='Цветовая схема затемнение'),
        ),
    ]
