# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-25 11:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('configuration', '0010_settings_odnoklassniky'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='banner_img',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_img', to=settings.FILER_IMAGE_MODEL, verbose_name='изображение в баннере'),
        ),
        migrations.AddField(
            model_name='settings',
            name='banner_text',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='текст баннера'),
        ),
    ]
