# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-26 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0011_auto_20181025_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeShipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Название')),
                ('show_address', models.BooleanField(default=True, verbose_name='Выводить поля ввода адреса')),
                ('calculation', models.CharField(choices=[('price_out', 'Высчитывается отдельно'), ('price_km', 'Цена за КМ'), ('price_fix', 'Фиксированная цена')], default='price_out', max_length=300, verbose_name='Способ рассчета')),
                ('price_km', models.FloatField(default=0, verbose_name='Цена за КМ')),
                ('price_fix', models.FloatField(default=0, verbose_name='Фиксированная цена')),
            ],
            options={
                'verbose_name': 'Способ доставки',
                'verbose_name_plural': 'Способы доставки',
                'ordering': ['id'],
            },
        ),
    ]
