# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0012_typeshipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeshipping',
            name='cities',
            field=models.TextField(blank=True, default='', verbose_name='Города с бесплатной доставкой'),
        ),
    ]
