# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-26 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0013_typeshipping_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeshipping',
            name='cities_free',
            field=models.TextField(blank=True, default='', verbose_name='Города с бесплатной доставкой'),
        ),
        migrations.AlterField(
            model_name='typeshipping',
            name='cities',
            field=models.TextField(blank=True, default='', verbose_name='Доставляется только в ...(города)'),
        ),
    ]
