# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-08 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0015_auto_20181028_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='bitrix24_domain',
            field=models.CharField(blank=True, default='', help_text='Пример: placestart.bitrix24.ru', max_length=100, verbose_name='Домен третьего уровня'),
        ),
        migrations.AddField(
            model_name='settings',
            name='bitrix24_key',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ключ вебхуков bitrix24'),
        ),
    ]
