# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-01 12:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('configuration', '0016_auto_20181108_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='seo_img',
        ),
        migrations.AddField(
            model_name='settings',
            name='seo_img1',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_img1', to=settings.FILER_IMAGE_MODEL, verbose_name='SEO картинка 1'),
        ),
        migrations.AddField(
            model_name='settings',
            name='seo_img2',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_img2', to=settings.FILER_IMAGE_MODEL, verbose_name='SEO картинка 2'),
        ),
        migrations.AddField(
            model_name='settings',
            name='seo_img3',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_img3', to=settings.FILER_IMAGE_MODEL, verbose_name='SEO картинка 3'),
        ),
    ]
