# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-04 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0017_auto_20190201_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Название')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='Адрес')),
                ('phones', models.CharField(blank=True, default='', help_text='разделитель ;', max_length=300, verbose_name='Номера телефонов')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('time_work', models.CharField(blank=True, default='', max_length=300, verbose_name='Режим работы')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_items', to='configuration.Settings', verbose_name='Настройки сайта')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
    ]
