# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-04 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0019_auto_20190204_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='image',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='settings',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
