# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-04 11:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('configuration', '0020_auto_20190204_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, default='', max_length=300, verbose_name='Подзаголовок')),
                ('link', models.CharField(blank=True, default='', max_length=100, verbose_name='Ссылка')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slider_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_items', to='configuration.Settings', verbose_name='Настройки сайта')),
            ],
            options={
                'verbose_name': 'Элемент слайдера',
                'ordering': ['id'],
                'verbose_name_plural': 'Слайдер',
            },
        ),
    ]
