# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-06 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300, verbose_name='Имя')),
                ('email', models.CharField(default='', max_length=300, verbose_name='Email')),
                ('message', models.CharField(default='', max_length=300, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
            },
        ),
    ]
