# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-11-11 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, verbose_name='Email')),
                ('subscription_exchange', models.BooleanField(default=False, verbose_name='subscription to 1C exchange service notifications')),
            ],
            options={
                'verbose_name': 'service email',
                'verbose_name_plural': 'service emails',
            },
        ),
    ]
