version: '3'
services:
  redis:
      image: redis
      ports:
        - "6379:6379"
  postgres:
    image: postgres:latest
    container_name: psql
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Golova123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  weberx:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media

    environment:
      - PYTHONUNBUFFERED=1
    command: gunicorn --bind 0.0.0.0:8000 system.wsgi:application

  nginx:
    build: 
      dockerfile: ./Dockerfile
      context: ./nginx/
    depends_on:
      - weberx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

    ports:
      - "80:80"

volumes:
  postgres_data:
  static_volume:
  media_volume:

