# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-08 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange1c', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='import_title',
            field=models.CharField(default=1, max_length=300, verbose_name='название файла импорта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='offers_title',
            field=models.CharField(default=1, max_length=300, verbose_name='название файла цен'),
            preserve_default=False,
        ),
    ]
