# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-30 18:52
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('exchange1c', '0002_auto_20180808_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='file',
            field=filer.fields.file.FilerFileField(null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File', verbose_name='Файл выгрузки'),
        ),
    ]
