# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-30 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange1c', '0003_settings_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='file',
            field=models.FileField(null=True, upload_to='./', verbose_name='Файл выгрузки'),
        ),
    ]
