# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-14 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange1c', '0004_auto_20180930_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='file',
        ),
    ]
