# Generated by Django 4.0.5 on 2022-06-01 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0016_alter_settings_color_scheme'),
        ('nav', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='object_href',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.hrefmodel', verbose_name='Ссылка на объект'),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
