# Generated by Django 4.0.5 on 2022-07-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0002_alter_navigation_level_alter_navigation_lft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
