# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-04 06:35
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('title', models.CharField(default='', max_length=300, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание акции')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Слаг')),
                ('date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='content.Content', verbose_name='Контент')),
                ('thumbnail', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_thumbnail', to=settings.FILER_IMAGE_MODEL, verbose_name='Минеатюра')),
            ],
            options={
                'verbose_name_plural': 'Акции',
                'verbose_name': 'акция',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст')),
                ('meta_title', models.CharField(blank=True, default='', max_length=300, verbose_name='SEO заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Meta Keywords')),
                ('active', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('title', models.CharField(default='', max_length=300, verbose_name='Заголовок')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Слаг')),
                ('template', models.IntegerField(choices=[(0, 'Обычная'), (1, 'Акции'), (2, 'Контакты')], default=0, verbose_name='Шаблон')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='content.Content', verbose_name='Контент')),
                ('original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.HrefModel', verbose_name='Оригинал')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='pages.Page', verbose_name='Родитель')),
                ('seo_img', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages_page_seo_img', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение')),
                ('thumbnail', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_thumbnail', to=settings.FILER_IMAGE_MODEL, verbose_name='Минеатюра')),
            ],
            options={
                'verbose_name_plural': 'Страницы',
                'verbose_name': 'страница',
            },
        ),
    ]
