# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-01 13:02
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='seo_img',
        ),
        migrations.AddField(
            model_name='page',
            name='seo_img1',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_page_seo_img1', to=settings.FILER_IMAGE_MODEL, verbose_name='SEO картинка 1'),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_img2',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_page_seo_img2', to=settings.FILER_IMAGE_MODEL, verbose_name='SEO картинка 2'),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_img3',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_page_seo_img3', to=settings.FILER_IMAGE_MODEL, verbose_name='SEO картинка 3'),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='SEO текст'),
        ),
    ]
