# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-26 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.FloatField(default=0, verbose_name='Стоимость доставки'),
        ),
    ]
