# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-28 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_shipping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_type_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Способ доставки'),
        ),
    ]
