# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-01 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20190201_1602'),
        ('shop', '0003_order_shipping_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Option', verbose_name='Опция'),
        ),
    ]
