# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-17 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cartitem_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='option',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='option_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id опции'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_id',
            field=models.IntegerField(default=0, verbose_name='id продукта'),
            preserve_default=False,
        ),
    ]
