# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-17 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20191014_1653'),
        ('shop', '0005_auto_20191017_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='option_id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Option', verbose_name='Опция'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='Товар'),
            preserve_default=False,
        ),
    ]
