# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-26 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20201123_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeshipping',
            name='min_price',
            field=models.FloatField(default=0, verbose_name='Минимальная сумма заказа'),
        ),
    ]
