# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-30 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_typeshipping_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeshipping',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
