# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-06-07 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_auto_20210319_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeshipping',
            name='code',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Код'),
        ),
    ]
