# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-10-10 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_slider_mobile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeshipping',
            name='display_motivational',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typeshipping',
            name='motivational_message',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Мотивационное сообщение'),
        ),
    ]
