# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-10-10 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_auto_20211010_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeshipping',
            name='display_motivational',
            field=models.BooleanField(default=False, verbose_name='Отображать мотивационное сообещение?'),
        ),
    ]
