# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2022-01-18 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0012_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='sort',
            field=models.IntegerField(default=1, verbose_name='Сортировка'),
        ),
    ]
