# Generated by Django 4.0.5 on 2022-06-01 13:46

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0015_contactemail_show_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='color_scheme',
            field=colorfield.fields.ColorField(default='#006EFF', help_text='HEX color, as #RRGGBB', image_field=None, max_length=7, samples=None, verbose_name='Цветовая схема сайта'),
        ),
    ]
