# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-04 06:35
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'сертификаты',
                'verbose_name': 'сертификат',
            },
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=1, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name_plural': 'Сертификаты',
                'verbose_name': 'сертификаты',
            },
        ),
        migrations.CreateModel(
            name='CertificatesBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name_plural': 'блоки сертификатов',
                'verbose_name': 'блок сертификатов',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name_plural': 'Контент',
                'verbose_name': 'Контент',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Подпись', max_length=300, verbose_name='Подпись')),
            ],
            options={
                'verbose_name_plural': 'файлы',
                'verbose_name': 'файл',
            },
        ),
        migrations.CreateModel(
            name='FileBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Подпись')),
            ],
            options={
                'verbose_name_plural': 'Блоки с файлами',
                'verbose_name': 'блок с файлами',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=1, verbose_name='Сортировка')),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.FileBlock', verbose_name='Блок файлов')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_files', to='content.Content')),
            ],
            options={
                'verbose_name_plural': 'Файлы',
                'verbose_name': 'файлы',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=1, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name_plural': 'галереи',
                'verbose_name': 'галерея',
            },
        ),
        migrations.CreateModel(
            name='GalleryBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок')),
                ('type_show', models.IntegerField(choices=[(6, 'Два'), (4, 'Три'), (3, 'Четыре')], default=6, verbose_name='Количество элементов в ряду')),
            ],
            options={
                'verbose_name_plural': 'Блок галереи',
                'verbose_name': 'Блок галереи ',
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='content.GalleryBlock')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение')),
            ],
            options={
                'verbose_name_plural': 'Элементы галереи',
                'verbose_name': 'элемент галереи',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', verbose_name='Цитата')),
                ('sort', models.IntegerField(default=1, verbose_name='Сортировка')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_quotes', to='content.Content')),
            ],
            options={
                'verbose_name_plural': 'цитаты',
                'verbose_name': 'цитата',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Текст')),
                ('sort', models.IntegerField(default=1, verbose_name='Сортировка')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_texts', to='content.Content')),
            ],
            options={
                'verbose_name_plural': 'Тексты',
                'verbose_name': 'текст',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='TitleUnderline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', verbose_name='Текст')),
                ('sort', models.IntegerField(default=1, verbose_name='Сортировка')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_title_underline', to='content.Content')),
            ],
            options={
                'verbose_name_plural': 'ползаголовки с подчеркиванием',
                'verbose_name': 'подзаголовок с подчеркиванием',
            },
        ),
        migrations.CreateModel(
            name='TypalBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=1, verbose_name='Сортировка')),
                ('title', models.CharField(default='', max_length=300, verbose_name='Заголовок')),
                ('text', models.TextField(default='', verbose_name='Текст')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_typal_block', to='content.Content')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typal_block_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение')),
            ],
            options={
                'verbose_name_plural': 'Типовые блоки',
                'verbose_name': 'типовой блок',
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.GalleryBlock', verbose_name='Галерея'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_gallery', to='content.Content'),
        ),
        migrations.AddField(
            model_name='file',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_items', to='content.FileBlock', verbose_name='Блок файлов'),
        ),
        migrations.AddField(
            model_name='file',
            name='obj',
            field=filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, related_name='file_objects', to='filer.File', verbose_name='файл'),
        ),
        migrations.AddField(
            model_name='certificates',
            name='block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.CertificatesBlock', verbose_name='Блок сертификатов'),
        ),
        migrations.AddField(
            model_name='certificates',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_certificates', to='content.Content'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_items', to='content.CertificatesBlock'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение'),
        ),
    ]
