# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-12-25 12:36
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_collapser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collapser',
            options={'verbose_name': 'Схлопывающийся блок', 'verbose_name_plural': 'Схлопывающиеся блоки'},
        ),
        migrations.AlterField(
            model_name='collapser',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Текст'),
        ),
    ]
