# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-04 09:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300, verbose_name='Имя')),
                ('email', models.CharField(default='', max_length=300, verbose_name='Email')),
                ('message', models.CharField(default='', max_length=300, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
            },
        ),
        migrations.CreateModel(
            name='serviceEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, verbose_name='Email')),
                ('subscription_exchange', models.BooleanField(default=False, verbose_name='subscription to 1C exchange service notifications')),
            ],
            options={
                'verbose_name': 'service email',
                'verbose_name_plural': 'service emails',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
    ]
