# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-08-13 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_loggingemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggingemail',
            name='exception_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
