# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-08-13 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_loggingemail_exception_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loggingemail',
            options={'verbose_name': 'Отчет об отправленном письме', 'verbose_name_plural': 'Отчеты об отправленных письмах'},
        ),
    ]
