# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-08-13 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20210813_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggingemail',
            name='date',
            field=models.DateTimeField(verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='loggingemail',
            name='exception_body',
            field=models.TextField(blank=True, null=True, verbose_name='Вывод ошибки'),
        ),
        migrations.AlterField(
            model_name='loggingemail',
            name='ok',
            field=models.BooleanField(default=False, verbose_name='Письмо отправлено'),
        ),
        migrations.AlterField(
            model_name='loggingemail',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Заголовок письма'),
        ),
        migrations.AlterField(
            model_name='loggingemail',
            name='to',
            field=models.EmailField(max_length=254, verbose_name='Адреса получателей'),
        ),
    ]
