# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-09 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='Наименование'),
        ),
    ]
