# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-09 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20181009_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='name',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Сериализованное значение'),
        ),
    ]
