# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-01 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_attribute_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(1, 'В наличии'), (2, 'Ожидается поступление'), (3, 'На заказ')], default=1, verbose_name='Статус'),
        ),
    ]
