# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-01 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190201_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='option',
            name='step',
            field=models.PositiveIntegerField(default=1, verbose_name='Шаг'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Единица измерения'),
        ),
    ]
