# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-04 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('catalog', '0010_auto_20190201_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, null=True, verbose_name='Наименование')),
                ('black_color', models.BooleanField(default=False, help_text='Иначе белый', verbose_name='Черный текст в карточке на главной')),
                ('thumbnail', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direction_thumbnail', to=settings.FILER_IMAGE_MODEL, verbose_name='Картинка')),
            ],
            options={
                'verbose_name_plural': 'Направления',
                'verbose_name': 'Направление',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='directions',
            field=models.ManyToManyField(blank=True, null=True, related_name='direction_products', to='catalog.Direction', verbose_name='Направления'),
        ),
    ]
