# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-04 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20190204_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='directions',
            field=models.ManyToManyField(blank=True, related_name='direction_products', to='catalog.Direction', verbose_name='Направления'),
        ),
    ]
