# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-06 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20190204_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='sort',
            field=models.PositiveIntegerField(default=500, verbose_name='Сортировка'),
        ),
    ]
