# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-11 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_direction_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['sort'], 'verbose_name': 'Направление', 'verbose_name_plural': 'Направления'},
        ),
    ]
