# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-11 09:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('catalog', '0014_auto_20190211_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='country',
        ),
        migrations.AddField(
            model_name='brand',
            name='thumbnail',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_thumbnail', to=settings.FILER_IMAGE_MODEL, verbose_name='Картинка'),
        ),
    ]
