# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-11 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20190211_1256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='BrandFile',
        ),
    ]
