# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-05 14:25
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20190211_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AddField(
            model_name='option',
            name='unloading_id',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Ид 1С'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Текст'),
        ),
    ]
