# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-14 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20190805_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='step',
            field=models.PositiveIntegerField(default=1, verbose_name='Шаг'),
        ),
    ]
