# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-28 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_product_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='title_original',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Оригинальное название'),
        ),
    ]
