# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-17 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_direction_title_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(1, 'В наличии'), (2, 'Ожидается поступление'), (3, 'Нет в наличии')], default=1, verbose_name='Статус'),
        ),
    ]
