# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-25 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20190917_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Единицы измерения'),
        ),
    ]
