# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-14 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_product_units'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'ordering': ['title'], 'verbose_name': 'Значение атрибута', 'verbose_name_plural': 'Значения атрибутов'},
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.FloatField(blank=True, default=0, verbose_name='Количество'),
        ),
    ]
