# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-14 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20191014_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='step',
            field=models.FloatField(default=1, verbose_name='Шаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='step',
            field=models.FloatField(default=1, verbose_name='Шаг'),
        ),
    ]
