# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-18 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20191018_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='level',
        ),
        migrations.RemoveField(
            model_name='option',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='option',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='option',
            name='tree_id',
        ),
    ]
