# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-11-18 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_auto_20191018_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_upper',
            field=models.CharField(default=models.CharField(db_index=True, max_length=300, null=True, verbose_name='Наименование'), max_length=300, null=True, verbose_name='Наименование UPPER'),
        ),
    ]
