# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-03-06 08:59
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_product_description_upper'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='text_upper',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Текст'), null=True, verbose_name='Текст UPPER'),
        ),
        migrations.AddField(
            model_name='brand',
            name='title_upper',
            field=models.CharField(default=models.CharField(default='', max_length=300, verbose_name='Заголовок'), max_length=300, null=True, verbose_name='Заголовок UPPER'),
        ),
    ]
