# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-18 11:28
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_auto_20200518_1419'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_content_b82ff0_gin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='content_search',
        ),
    ]
