# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-19 10:48
from __future__ import unicode_literals

import ckeditor_uploader.fields
import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_auto_20200518_1428'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_upper'], name='catalog_pro_title_u_901f43_gin'),
        ),
    ]
