# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-19 11:14
from __future__ import unicode_literals

import ckeditor_uploader.fields
import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_auto_20200519_1348'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_title_u_901f43_gin',
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_upper', 'description_upper', 'code'], name='catalog_pro_title_u_aff2bb_gin'),
        ),
    ]
