# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-19 11:17
from __future__ import unicode_literals

import ckeditor_uploader.fields
import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_auto_20200519_1414'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='brand',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_upper'], name='catalog_bra_title_u_7977b4_gin'),
        ),
    ]
