# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-20 12:08
from __future__ import unicode_literals

import ckeditor_uploader.fields
import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_auto_20200519_1417'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='catalog_cat_title_a636fb_gin'),
        ),
    ]
