# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-04 08:31
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_auto_20200520_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='product',
            name='search_vector',
        ),
        migrations.AlterField(
            model_name='brand',
            name='text_upper',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Текст'), null=True, verbose_name='Текст UPPER'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=3000, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_upper',
            field=models.CharField(db_index=True, default=models.CharField(max_length=3000, null=True, verbose_name='Наименование'), max_length=3000, null=True, verbose_name='Наименование UPPER'),
        ),
    ]
