# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-10-08 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company_inn',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='account',
            name='company_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название компании'),
        ),
    ]
