# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-05-06 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201008_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='jurical',
            field=models.BooleanField(default=False, verbose_name='Является юр. лицом'),
        ),
    ]
