# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-05-06 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_jurical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='company_inn',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='ИНН'),
        ),
    ]
