# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-05-06 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210506_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон'),
        ),
    ]
