# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-05-07 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210506_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
    ]
