# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-05-12 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210507_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='account.Manager', verbose_name='Менеджер'),
        ),
    ]
