# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-05-13 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210512_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджеры'},
        ),
        migrations.AddField(
            model_name='account',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='account',
            name='surname',
            field=models.CharField(default='', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
