# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-05-25 16:41
from __future__ import unicode_literals

import apps.catalog.models.price
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20210525_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='price_type',
            field=models.ForeignKey(default=apps.catalog.models.price.get_default_price_type, on_delete=django.db.models.deletion.CASCADE, to='catalog.PriceType', verbose_name='Отображаемый тип цены'),
        ),
    ]
