# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-05-27 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_discountcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='discount_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='account.DiscountCard', verbose_name='Скидочная карта'),
        ),
    ]
