# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-05-27 13:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20210527_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='points_total',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество баллов'),
        ),
    ]
