# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-05-28 11:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_account_points_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='unconfirmed_points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Неподтвержденные баллы'),
        ),
    ]
