# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-05-28 11:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_account_unconfirmed_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='unconfirmed_points',
            field=models.IntegerField(default=0, help_text='\n            Эти баллы перейдут на основной счет баллов пользователя,\n            после подтверждения оплаты\n            ', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Неподтвержденные баллы'),
        ),
    ]
