# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-05-31 11:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20210528_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcard',
            options={'verbose_name': 'Бонусная карта', 'verbose_name_plural': 'Бонусные карты'},
        ),
        migrations.AlterField(
            model_name='account',
            name='unconfirmed_points',
            field=models.IntegerField(default=0, help_text='\n            Эти баллы будут постепенно переходить на основной\n            бонусный счет пользователя,\n            по мере оплаты им его заказов\n            ', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Неподтвержденные баллы'),
        ),
    ]
