# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-07-13 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20210629_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bonus_card_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ИД бонусной карты'),
        ),
    ]
