# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-08-14 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_account_bonus_card_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('min_limit', models.PositiveIntegerField(verbose_name='Минимальный порог')),
                ('max_limit', models.PositiveIntegerField(verbose_name='Максимальный порог')),
                ('previous_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AccountStatus', verbose_name='Предыдущий статус')),
            ],
        ),
    ]
