# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-08-14 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_accountstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatus',
            name='previous_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.AccountStatus', verbose_name='Предыдущий статус'),
        ),
    ]
