# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-08-14 13:18
from __future__ import unicode_literals

import apps.account.models.Status
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20210814_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.ForeignKey(default=apps.account.models.Status.AccountStatus.default, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='accounts', to='account.AccountStatus', verbose_name='Статус'),
        ),
    ]
