# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-08-15 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20210815_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatus',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
