# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-08-16 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20210815_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='id_1c',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ИД из 1с'),
        ),
    ]
