# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-08-16 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_account_id_1c'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='clear_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Полное имя'),
        ),
    ]
