# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-10-14 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_accountstatus_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contract_balance',
            field=models.FloatField(default=0, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='account',
            name='contract_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Наименование договора'),
        ),
    ]
