# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-10-14 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_auto_20211014_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contract_type',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Тип договора'),
        ),
    ]
