# Generated by Django 4.0.6 on 2023-09-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_alter_account_id_alter_accountstatus_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountstatus',
            name='code',
        ),
    ]
