# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-30 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200630_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='count_cherepovets',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='count_vologda',
        ),
    ]
