# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-08-28 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_is_imported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_imported',
        ),
        migrations.AddField(
            model_name='order',
            name='status_imported',
            field=models.CharField(choices=[('not_upload', 'Не выгружен'), ('upload', 'Выгружен'), ('processing', 'В процессе')], default='not_upload', editable=False, max_length=25, verbose_name='Загружены в 1С'),
        ),
    ]
