# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-09-09 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200828_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес магазина'),
        ),
    ]
