# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-09-21 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_shop_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company_inn',
            field=models.CharField(blank=True, default='', max_length=125, verbose_name='ИНН компании'),
        ),
        migrations.AddField(
            model_name='order',
            name='company_title',
            field=models.CharField(blank=True, default='', max_length=125, verbose_name='Название компании'),
        ),
    ]
