# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-09-22 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200921_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_file',
            field=models.FileField(blank=True, default='', upload_to='files/payment/', verbose_name='Файл'),
        ),
    ]
