# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-09-22 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_payment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_file',
            field=models.FileField(blank=True, default='', upload_to='files/payment/', verbose_name='Реквизиты'),
        ),
    ]
