# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-26 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200922_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='entrance',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.CharField(choices=[('self', 'Самовывоз'), ('transport', 'Транспотной компанией'), ('post', 'Почтой'), ('courier', 'Курьером'), ('dostavka', 'Доставка')], default='self', max_length=50, verbose_name='Доставка'),
        ),
    ]
