# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-26 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201226_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Телефон'),
        ),
    ]
