# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-03-03 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20201226_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_imported',
            field=models.CharField(choices=[('doNotUpload', 'Не подлежит выгрузке'), ('not_upload', 'Не выгружен'), ('upload', 'Выгружен'), ('processing', 'В процессе')], default='not_upload', max_length=25, verbose_name='Загружены в 1С'),
        ),
    ]
