# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-05-13 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210303_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Фамилия'),
        ),
    ]
