# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-05-14 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20210513_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='jurical',
            field=models.BooleanField(default=False, verbose_name='Заказ от юр. лица'),
        ),
    ]
