# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-05-28 12:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_order_jurical'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='points_spent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество потраченных бонусов'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_without_points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость заказа без вычета бонусов'),
        ),
    ]
