# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-05-28 13:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210528_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='points_collected',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество баллов, которые пользователь получит после оплаты'),
        ),
    ]
