# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-06-22 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_order_points_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Заказ удален?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('completed', 'Выполнен'), ('canceled', 'Отменен'), ('stash', 'Сохранен')], default='processing', max_length=50, verbose_name='Статус'),
        ),
    ]
