# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-07-14 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20210525_1910'),
        ('shop', '0020_auto_20210629_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_order_items', to='catalog.Option', verbose_name='Характеристка товара'),
        ),
    ]
