# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-08-15 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_orderitem_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('code', models.CharField(max_length=200, unique=True, verbose_name='Код')),
                ('position', models.PositiveIntegerField()),
            ],
        ),
    ]
