# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-08-15 13:38
from __future__ import unicode_literals

import apps.shop.models.order_state
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_order_current_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='сompleted_states',
            field=models.ManyToManyField(related_name='passed_orders', to='shop.OrderState', verbose_name='Выполненные состояния'),
        ),
        migrations.AlterField(
            model_name='order',
            name='current_state',
            field=models.ForeignKey(default=apps.shop.models.order_state.OrderState.default, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='orders', to='shop.OrderState', verbose_name='Текущее состояние заказа'),
        ),
    ]
