# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-08-15 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20210815_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstate',
            options={'verbose_name': 'Состояние заказа', 'verbose_name_plural': 'Состояния заказа'},
        ),
        migrations.AlterField(
            model_name='orderstate',
            name='code',
            field=models.CharField(choices=[('000000001', 'Принят'), ('000000002', 'Зарезервирован'), ('000000003', 'Ожидает оплаты'), ('000000008', 'Ожидает подтверждения'), ('000000004', 'Оплачен'), ('000000005', 'Отгружен частично'), ('000000006', 'Отгружен полностью'), ('000000007', 'Отменен')], default='000000001', max_length=200, unique=True, verbose_name='Код'),
        ),
    ]
