# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-08-15 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20210815_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstate',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Состояние заказа', 'verbose_name_plural': 'Состояния заказа'},
        ),
    ]
