# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-08-16 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20210815_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='сompleted_states',
            new_name='completed_states',
        ),
    ]
