# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-08-17 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20210816_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstate',
            name='color',
            field=models.CharField(default='#f5a623', help_text='Цвет, которым будет выделен статус в ЛК', max_length=200, verbose_name='Цвет'),
        ),
    ]
