# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2022-03-05 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('shop', '0031_auto_20210817_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, verbose_name='Дата')),
                ('log_file', filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, related_name='order_log_files', to='filer.File', verbose_name='Лог')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Лог-файл заказа',
                'verbose_name_plural': 'Лог-файлы заказа',
            },
        ),
    ]
