# Generated by Django 4.0.5 on 2022-06-01 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_alter_attribute_group_alter_attribute_product_and_more'),
        ('account', '0034_alter_accountstatus_previous_status'),
        ('shop', '0033_auto_20220311_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.option', verbose_name='Опция'),
        ),
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='account.account', verbose_name='Профиль'),
        ),
    ]
