# Generated by Django 4.0.5 on 2022-06-01 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('content', '0002_galleryitem_backing_image'),
        ('configuration', '0016_alter_settings_color_scheme'),
        ('pages', '0003_auto_20210902_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='content.content', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='thumbnail',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_thumbnail', to=settings.FILER_IMAGE_MODEL, verbose_name='Минеатюра'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='content.content', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='page',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.hrefmodel', verbose_name='Оригинал'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childs', to='pages.page', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='page',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_img1',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_seo_img1', to=settings.FILER_IMAGE_MODEL, verbose_name='SEO картинка 1'),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_img2',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_seo_img2', to=settings.FILER_IMAGE_MODEL, verbose_name='SEO картинка 2'),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_img3',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_seo_img3', to=settings.FILER_IMAGE_MODEL, verbose_name='SEO картинка 3'),
        ),
        migrations.AlterField(
            model_name='page',
            name='thumbnail',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_thumbnail', to=settings.FILER_IMAGE_MODEL, verbose_name='Минеатюра'),
        ),
    ]
