# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-29 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='Продукт')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.City', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Остатки на складе',
                'verbose_name_plural': 'Остатки на складах',
                'ordering': ['product'],
            },
        ),
    ]
