# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-29 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productstorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStorageCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Остатки на складе',
                'verbose_name_plural': 'Остатки на складах',
                'ordering': ['product'],
            },
        ),
        migrations.AlterModelOptions(
            name='productstorage',
            options={'ordering': ['storage'], 'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.RemoveField(
            model_name='productstorage',
            name='count',
        ),
        migrations.RemoveField(
            model_name='productstorage',
            name='product',
        ),
        migrations.AddField(
            model_name='productstorage',
            name='title',
            field=models.CharField(default='', max_length=127, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productstorage',
            name='upload_title',
            field=models.CharField(default='', max_length=127, unique=True, verbose_name='Название в выгрузке'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productstoragecount',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ProductStorage', verbose_name='Склад'),
        ),
    ]
