# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-29 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200629_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstorage',
            options={'ordering': ['city'], 'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.RenameField(
            model_name='productstorage',
            old_name='storage',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='productstorage',
            name='title',
            field=models.CharField(default='', max_length=127, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productstorage',
            name='upload_title',
            field=models.CharField(default='', max_length=127, unique=True, verbose_name='Название в выгрузке'),
        ),
        migrations.AlterField(
            model_name='productstoragecount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='catalog.Product', verbose_name='Продукт'),
        ),
    ]
