# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-29 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200629_1520'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productstoragecount',
            unique_together=set([('storage', 'product')]),
        ),
    ]
