# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-29 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200629_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstoragecount',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='catalog.Option', verbose_name='Вариативный товар'),
        ),
        migrations.AlterField(
            model_name='productstoragecount',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='catalog.Product', verbose_name='Продукт'),
        ),
    ]
