# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-29 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200629_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstorage',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.City', verbose_name='Город'),
        ),
        migrations.AlterUniqueTogether(
            name='productstoragecount',
            unique_together=set([]),
        ),
    ]
