# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-07-06 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200706_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delete_options',
            field=models.BooleanField(default=False, editable=False, verbose_name='Опции удалены'),
        ),
    ]
