# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-07-06 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_delete_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delete_options',
        ),
    ]
