# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-07-13 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_product_delete_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_clear_options',
            field=models.BooleanField(default=False, editable=False, verbose_name='Опции были удалены'),
        ),
    ]
