# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-07-17 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_is_clear_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstoragecount',
            name='count',
            field=models.FloatField(verbose_name='Количество'),
        ),
    ]
