# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-07-20 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200720_0949'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='option',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='price_type',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductPrice',
        ),
        migrations.DeleteModel(
            name='ProductPriceType',
        ),
    ]
