# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-08-28 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_product_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort'], 'verbose_name': 'товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
