# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-10-05 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20200910_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активность'),
        ),
    ]
