# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-10-08 09:40
from __future__ import unicode_literals

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20201005_1637'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_title_u_aff2bb_gin',
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'title_upper', 'description_upper', 'code'], name='catalog_pro_title_adc47d_gin'),
        ),
    ]
