# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-10-12 12:05
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20201008_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
    ]
