# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-03-03 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20201226_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstorage',
            name='address',
            field=models.CharField(default=models.CharField(default='', max_length=127, verbose_name='Название'), max_length=127, verbose_name='Адрес'),
        ),
    ]
