# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-03-23 13:35
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('catalog', '0025_auto_20210303_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='SEO заголовок'),
        ),
        migrations.AddField(
            model_name='brand',
            name='seo_img1',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_brand_seo_img1', to=settings.FILER_IMAGE_MODEL, verbose_name='SEO картинка 1'),
        ),
        migrations.AddField(
            model_name='brand',
            name='seo_img2',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_brand_seo_img2', to=settings.FILER_IMAGE_MODEL, verbose_name='SEO картинка 2'),
        ),
        migrations.AddField(
            model_name='brand',
            name='seo_img3',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_brand_seo_img3', to=settings.FILER_IMAGE_MODEL, verbose_name='SEO картинка 3'),
        ),
        migrations.AddField(
            model_name='brand',
            name='seo_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='SEO текст'),
        ),
    ]
