# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-05-24 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20210430_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('a6bfe5d1-ccce-11dd-8d29-001fc6b4b87e', 'Розница'), ('a6bfe5d2-ccce-11dd-8d29-001fc6b4b87e', 'Оптовая')], default='a6bfe5d1-ccce-11dd-8d29-001fc6b4b87e', max_length=150, verbose_name='Тип цены')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Значение цены')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
    ]
