# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-05-24 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='old_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Старая цена'),
        ),
    ]
