# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-05-24 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_productprice_old_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together=set([('type', 'product')]),
        ),
    ]
