# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-05-25 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_auto_20210524_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id_1c', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Идентификатор из 1с')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование типа цены')),
            ],
        ),
        migrations.AlterField(
            model_name='productprice',
            name='type',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.PriceType', verbose_name='Тип цены'),
        ),
    ]
