# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-07-17 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20210525_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Значение цены')),
                ('old_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Старое значение цены')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.Option', verbose_name='Характеристика')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.PriceType', verbose_name='Тип цены')),
            ],
            options={
                'verbose_name': 'Цена характеристики',
                'verbose_name_plural': 'Цены характеристик',
            },
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'verbose_name': 'Цена товара', 'verbose_name_plural': 'Цены товаров'},
        ),
        migrations.AlterUniqueTogether(
            name='optionprice',
            unique_together=set([('type', 'option')]),
        ),
    ]
