# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-08-02 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_auto_20210717_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='Приоритет'),
        ),
    ]
