# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-09-13 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_auto_20210802_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alt_title',
            field=models.CharField(blank=True, help_text=('Заголовок, который', 'будет выводиться на страницах,', 'прим. страница с направлениями'), max_length=200, null=True, verbose_name='Альтернативное наименование'),
        ),
    ]
