# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2022-01-20 14:24
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_auto_20220120_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='title_original',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Оригинальное название'),
        ),
    ]
