# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2022-01-20 14:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('catalog', '0040_auto_20220120_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='mobile_thumbnail',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direction_thumbnail_mobile', to=settings.FILER_IMAGE_MODEL, verbose_name='Картинка для телефонов'),
        ),
    ]
