# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2022-02-28 10:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('catalog', '0043_indexblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexblock',
            name='image',
        ),
        migrations.AddField(
            model_name='indexblock',
            name='image_left_bottom',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_block_images_left_bottom', to=settings.FILER_IMAGE_MODEL, verbose_name='Картинка в левом нижнем углу'),
        ),
        migrations.AddField(
            model_name='indexblock',
            name='image_right_bottom',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_block_images_right_bottom', to=settings.FILER_IMAGE_MODEL, verbose_name='Картинка в правом нижнем углу'),
        ),
        migrations.AddField(
            model_name='indexblock',
            name='image_right_top',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_block_images_right_top', to=settings.FILER_IMAGE_MODEL, verbose_name='Картинка в правом верхнем углу'),
        ),
    ]
