# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2022-02-28 10:10
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_auto_20220228_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexblock',
            name='image_left_bottom',
            field=filer.fields.file.FilerFileField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_block_images_left_bottom', to='filer.File', verbose_name='Картинка в левом нижнем углу'),
        ),
        migrations.AlterField(
            model_name='indexblock',
            name='image_right_bottom',
            field=filer.fields.file.FilerFileField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_block_images_right_bottom', to='filer.File', verbose_name='Картинка в правом нижнем углу'),
        ),
        migrations.AlterField(
            model_name='indexblock',
            name='image_right_top',
            field=filer.fields.file.FilerFileField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_block_images_right_top', to='filer.File', verbose_name='Картинка в правом верхнем углу'),
        ),
    ]
