# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2022-02-28 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_auto_20220228_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexblock',
            name='is_clickable',
            field=models.BooleanField(default=True, verbose_name='Ссылка работает?'),
        ),
    ]
