# Generated by Django 4.0.6 on 2022-08-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_alter_attribute_id_alter_attributesgroup_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributesgroup',
            name='show_in_header',
            field=models.BooleanField(default=False, verbose_name='Показывать фильтр в шапке каталога'),
        ),
    ]
