# Generated by Django 4.0.6 on 2022-09-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0050_attributesgroup_show_in_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_related_categories_and_filters',
            field=models.BooleanField(default=True, verbose_name='Показывать кнопки категорий и фильтров в заголовке каталога'),
        ),
    ]
