# Generated by Django 4.1.5 on 2023-02-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0051_category_display_related_categories_and_filters"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="display_related_categories",
            field=models.BooleanField(
                default=True,
                verbose_name="Показывать кнопки категорий в заголовке каталога",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="display_related_categories_and_filters",
            field=models.BooleanField(
                default=True,
                verbose_name="Показывать кнопки фильтров в заголовке каталога",
            ),
        ),
    ]
