# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-11-09 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='primary_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка'),
        ),
    ]
