# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-11-11 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_primary_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='primary_link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
