# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-11-15 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211111_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Миниатюра'),
        ),
    ]
